--<ScriptOptions statementTerminator=";"/>

CREATE TABLE UTILISATEUR (
		IDUSER NUMBER(10 , 0) NOT NULL,
		LOGIN VARCHAR2(60) NOT NULL,
		MDP VARCHAR2(60)
	);

CREATE TABLE CB (
		NUMCB NUMBER(10 , 0) NOT NULL,
		TYPE VARCHAR2(25),
		NUMCOMPTE NUMBER(10 , 0)
	);

CREATE TABLE CONSEILLER (
		IDCONS NUMBER(10 , 0) NOT NULL,
		NOM VARCHAR2(60),
		PRENOM VARCHAR2(60) NOT NULL,
		IDUSER NUMBER(10 , 0),
		IDAGENCE NUMBER(10 , 0),
		LOGIN VARCHAR2(20),
		MDP VARCHAR2(20)
	);

CREATE TABLE AGENCE (
		IDAGENCE NUMBER(10 , 0) NOT NULL,
		DATECREATION DATE,
		IDCONS NUMBER(10 , 0),
		NOM VARCHAR2(60)
	);

CREATE TABLE CLIENT (
		IDCLIENT NUMBER(10 , 0) NOT NULL,
		NOM VARCHAR2(60) NOT NULL,
		PRENOM VARCHAR2(60),
		ADRESSE VARCHAR2(60),
		CODEPOSTAL VARCHAR2(25),
		VILLE VARCHAR2(60),
		TELEPHONE VARCHAR2(25),
		IDCONS NUMBER(10 , 0)
	);

CREATE TABLE PLACEMENT (
		IDPLACEMENT NUMBER(10 , 0) NOT NULL,
		BOURSE VARCHAR2(25),
		MONTANT NUMBER,
		IDCLIENT NUMBER(10 , 0)
	);

CREATE TABLE COMPTE (
		NUMCOMPTE NUMBER(10 , 0) NOT NULL,
		TYPE VARCHAR2(25),
		SOLDE NUMBER,
		TAUX FLOAT(126),
		AUTODECOUVERT NUMBER,
		IDCLIENT NUMBER(10 , 0)
	);

CREATE UNIQUE INDEX PLACEMENT_PK ON PLACEMENT (IDPLACEMENT ASC);

CREATE UNIQUE INDEX AGENCE_PK ON AGENCE (IDAGENCE ASC);

CREATE UNIQUE INDEX CLIENT_PK ON CLIENT (IDCLIENT ASC);

CREATE UNIQUE INDEX CONSEILLER_PK ON CONSEILLER (IDCONS ASC);

CREATE UNIQUE INDEX COMPTE_PK ON COMPTE (NUMCOMPTE ASC);

CREATE UNIQUE INDEX UN_NOM_PRENOM ON CONSEILLER (NOM ASC, PRENOM ASC);

CREATE UNIQUE INDEX CB_PK ON CB (NUMCB ASC);

CREATE UNIQUE INDEX UN_IDUSER ON CONSEILLER (IDUSER ASC);

ALTER TABLE AGENCE ADD CONSTRAINT AGENCE_PK PRIMARY KEY (IDAGENCE);

ALTER TABLE CB ADD CONSTRAINT CB_PK PRIMARY KEY (NUMCB);

ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_PK PRIMARY KEY (IDCLIENT);

ALTER TABLE PLACEMENT ADD CONSTRAINT PLACEMENT_PK PRIMARY KEY (IDPLACEMENT);

ALTER TABLE CONSEILLER ADD CONSTRAINT CONSEILLER_PK PRIMARY KEY (IDCONS);

ALTER TABLE COMPTE ADD CONSTRAINT COMPTE_PK PRIMARY KEY (NUMCOMPTE);

ALTER TABLE COMPTE ADD CONSTRAINT FK_COMPTE_IDCLIENT FOREIGN KEY (IDCLIENT)
	REFERENCES CLIENT (IDCLIENT);


ALTER TABLE PLACEMENT ADD CONSTRAINT FK_PLACEMENT_IDCLIENT FOREIGN KEY (IDCLIENT)
	REFERENCES CLIENT (IDCLIENT);


ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_IDCONS FOREIGN KEY (IDCONS)
	REFERENCES CONSEILLER (IDCONS);


ALTER TABLE CONSEILLER ADD CONSTRAINT FK_CONSEILLER_IDAGENCE FOREIGN KEY (IDAGENCE)
	REFERENCES AGENCE (IDAGENCE);


ALTER TABLE CB ADD CONSTRAINT FK_CB_NUMCOMPTE FOREIGN KEY (NUMCOMPTE)
	REFERENCES COMPTE (NUMCOMPTE);

CREATE SEQUENCE seq_idcons;
CREATE SEQUENCE seq_iduser;
CREATE SEQUENCE seq_idclient;
CREATE SEQUENCE seq_numcompte;

ALTER TABLE compte ADD dateouverture date;

	

