--<ScriptOptions statementTerminator=";"/>

CREATE USER proxibanque identified by proxipass;
grant resource, create sequence, create session, connect to proxibanque;
connect proxibanque/proxipass;

CREATE TABLE CLIENT (
		IDCLIENT NUMBER(10 , 0) NOT NULL,
		NOM VARCHAR2(60) NOT NULL,
		PRENOM VARCHAR2(60),
		ADRESSE VARCHAR2(60),
		CODEPOSTAL VARCHAR2(25),
		VILLE VARCHAR2(60),
		TELEPHONE VARCHAR2(25),
		IDCONS NUMBER(10 , 0)
	);

CREATE TABLE CONSEILLER (
		IDCONS NUMBER(10 , 0) NOT NULL,
		NOM VARCHAR2(60) NOT NULL,
		PRENOM VARCHAR2(60),
		IDAGENCE NUMBER(10 , 0),
		LOGIN VARCHAR2(20),
		MDP VARCHAR2(20)
	);

CREATE TABLE COMPTE (
		NUMCOMPTE NUMBER(10 , 0) NOT NULL,
		TYPE VARCHAR2(25),
		SOLDE NUMBER,
		TAUX FLOAT(126),
		AUTODECOUVERT NUMBER,
		IDCLIENT NUMBER(10 , 0),
		DATEOUVERTURE DATE
	);


CREATE UNIQUE INDEX CLIENT_PK ON CLIENT (IDCLIENT ASC);

CREATE UNIQUE INDEX UN_NOM_PRENOM ON CONSEILLER (NOM ASC, PRENOM ASC);

CREATE UNIQUE INDEX COMPTE_PK ON COMPTE (NUMCOMPTE ASC);

CREATE UNIQUE INDEX CONSEILLER_PK ON CONSEILLER (IDCONS ASC);

ALTER TABLE COMPTE ADD CONSTRAINT COMPTE_PK PRIMARY KEY (NUMCOMPTE);

ALTER TABLE CLIENT ADD CONSTRAINT CLIENT_PK PRIMARY KEY (IDCLIENT);

ALTER TABLE CONSEILLER ADD CONSTRAINT CONSEILLER_PK PRIMARY KEY (IDCONS);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_IDCONS FOREIGN KEY (IDCONS)
	REFERENCES CONSEILLER (IDCONS)
	ON DELETE CASCADE;

ALTER TABLE COMPTE ADD CONSTRAINT FK_COMPTE_IDCLIENT FOREIGN KEY (IDCLIENT)
	REFERENCES CLIENT (IDCLIENT)
	ON DELETE CASCADE;

CREATE SEQUENCE seq_idcons;
CREATE SEQUENCE seq_idclient;
CREATE SEQUENCE seq_numcompte;
